
PHASE_LOWER_MODULES = mpi_dummy.o m_Const_Parameters.o m_ErrorMessages.o m_Parallelization.o \
m_IterationNumbers.o

PHASE_UPPER_MODULES = \
m_Spg_plus_Tetra_Common_Blocks.o \
m_Control_Parameters.o   m_Files.o                m_Timing.o \
m_Crystal_Structure.o    m_FFT.o                  m_Ionic_System.o \
m_CS_SpaceGroup.o        m_CS_Magnetic.o \
m_Orbital_QuantumNum.o  \
m_Kpoints.o              m_PseudoPotential.o      m_PlaneWaveBasisSet.o \
m_Realspace.o \
m_SpinOrbit_Potential.o  m_SpinOrbit_FromFile.o  \
m_ES_NonCollinear.o \
m_NonLocal_Potential.o   m_Electronic_Structure.o \
m_ES_nonlocal.o	 	 m_ES_ortho.o  m_ES_wf_extrpl.o m_ES_initialWF.o 	\
m_ES_occup.o \
m_ES_RSB.o \
m_FiniteElectricField.o \
m_ES_ExactExchange.o \
m_ES_WF_by_SDorCG.o      m_ES_WF_by_Davidson.o \
m_ES_WF_by_ModifiedDavidson.o m_ES_WF_by_RMM.o \
m_Charge_Density.o  m_CD_Mag_Moment.o m_Orbital_Population.o      m_Dipole.o  m_CD_mixing.o \
m_PS_opencore.o \
m_epc_potential.o        \
m_Positron_Wave_Functions.o \
m_ES_WF_mixing.o \
m_Screening_FFT.o        m_Screening.o      m_External_Potential.o \
m_ES_LHXC.o              m_ES_Intgr_VlhxcQlm.o    m_ES_IO.o \
m_Representation.o       m_OP_rotation.o          m_OP_decomp_band.o \
m_ES_WF_by_MatDiagon.o   m_ES_dos.o               m_Hubbard.o \
m_KineticEnergy_Density.o  \
m_KE_mixing.o \
m_vdWDF.o \
m_Ldos.o                 m_XC_Potential.o         \
string.o m_db.o \
m_PAW_Tecplot.o m_PAW_ChargeDensity.o m_PAW_Hartree.o  \
m_PAW_XC_Potential.o \
m_SpinOrbit_RadInt.o \
m_OP_Moment.o \
m_ES_Mag_Constraint.o  \
m_Total_Energy.o \
m_Force.o                m_Stress.o               m_ES_WF_by_submat.o \
m_UnitCell.o \
m_constraints.o \
m_ELF.o \
m_BerryPhase.o           m_BP_Properties.o \
m_Raman.o            m_Phonon.o \
m_Wannier.o m_Wannier90.o m_Replica.o Renewal_of_ChgCtrlParam.o \
m_dimer.o \
m_LinearResponse_Control.o  \
m_ValenceBand_Spectrum.o   m_CoreLevel_Spectrum.o   \
m_Excitation.o \
m_CLS_dipquad.o m_ES_occup_EPS.o         m_Epsilon_ek.o \
m_LinearResponse_Qpt.o  \
m_ES_ChargeState.o \
m_rttddft.o \
m_Potential_Mixing.o       m_ThomasFermiW_Potential.o  \
m_SpinOrbit_SecondVariation.o m_Crystal_Field.o \
m_PlaneWaveEDA.o \
m_Fcp.o m_Band_Unfolding.o  m_Potential_Average.o

PHASE_F_SUBROUTINES = Preparation.o \
InputData_Analysis.o           PseudoPotential_Construction.o \

PHASE_F_OTHERSUBS  = mdmain0.o    constraint_main.o meta_dynamics.o  NEB.o Preparation_for_mpi.o \
Preparation_for_ESM.o \
scf_routines.o \
UnitaryTransform_WF.o \
bottom_Subroutines.o              \
spline.o \
b_Crystal_Structure.o             b_Electronic_Structure.o \
b_Words.o                         b_PseudoPotential.o \
b_PseudoPotential_EXX.o \
b_Fermi.o                         b_Kpoints.o \
b_PlaneWaveBasisSet.o             b_Ionic_System.o \
b_XC_Potential.o                  b_PAW_XC_Potential.o \
b_XC_OmegaPBE.o  \
b_XC_metagga.o \
b_Ldos_f77.o\
input_interface.o                 Initialization.o \
WriteDownData_onto_Files.o        Ewald_and_Structure_Factor.o \
Initial_Electronic_Structure.o \
Renewal_of_WaveFunctions.o \
Renewal_of_pWaveFunctions.o \
Uramping.o \
IterationNumbers_Setting.o        ChargeDensity_Construction.o \
ChargeDensity_Mixing.o            Renewal_of_Potential.o \
Renewal_of_Hubbard_Potential.o    Renewal_of_OccMat.o \
Renewal_of_pPotential.o           Renewal_of_Hubbard_Parameters.o \
Convergence_Check.o               Forces.o \
Move_Ions.o                       Initial_MD_Condition.o \
Stress.o                          Postprocessing.o \
Finalization_of_mpi.o             miscellaneous.o\
b_BerryPhase.o \
heap_sort.o                       real_spherical_harmonics.o \
Real_space_integ.o                crotylm.o \
screening_correction.o \
Initialization_Epsilon.o               Shift_Kpoint.o \
Reset_Kpoint.o                         Preparation_for_Calc_Epsilon.o \
Transition_moment_Epsilon.o            Calc_Epsilon.o \
Nonlinear_Optics_Epsilon.o             WriteDownData_onto_Files_Epsilon.o \
PseudoPotential_ek_Epsilon.o           Dealloc_Radr_and_Wos_Epsilon.o \
                                       WriteDownData_onto_Files_ek.o \
GaussLeg.o lib_int_deri_add.o  \
rttddft_main.o \
Potential_Construction.o        Potential_Mixing.o             ThomasFermiWeiz.o \
Epsilon_postscf.o vdW.o Epsilon_Paramset.o EPS_Prep_Check.o memsize.o scdft_routines.o

PHASE_INTERFACE = phase0_interface.o

# for vc_nl
NLOBJ = vc_nl.o

#
ifdef LIBXC
EXT_XC_OBJ = b_XC_libxc.o
else
EXT_XC_OBJ =
endif

ifndef SX_DGEMM
PHASE_OBJECTSF77 = \
b_PseudoPotential_f77.o \
b_Force_f77.o \
rmmsubs.o \
gncpp_xc_gga_rad.o  \
decfft_ent.o \
spg+tetra.o
else
PHASE_OBJECTSF77 = \
b_PseudoPotential_f77.o \
b_Force_f77.o \
rmmsubs.o \
decfft_ent.o \
gncpp_xc_gga_rad.o  \
spg+tetra.o \
dgemm__.o 
endif

EKCAL_LOWER_MODULES = m_Const_Parameters.o   m_ErrorMessages.o m_Parallelization.o \
m_IterationNumbers.o

EKCAL_UPPER_MODULES = \
m_Spg_plus_Tetra_Common_Blocks.o \
m_Control_Parameters.o   m_Files.o                m_Timing.o \
m_Crystal_Structure.o    m_FFT.o                  m_Ionic_System.o \
m_CS_SpaceGroup.o        m_CS_Magnetic.o \
m_Orbital_QuantumNum.o  \
m_Kpoints.o              m_PseudoPotential.o      m_PlaneWaveBasisSet.o \
m_Realspace.o \
m_SpinOrbit_Potential.o  m_SpinOrbit_FromFile.o  \
m_ES_NonCollinear.o \
m_NonLocal_Potential.o   m_Electronic_Structure.o \
m_ES_nonlocal.o	 	 m_ES_ortho.o  m_ES_wf_extrpl.o m_ES_initialWF.o 	\
m_FiniteElectricField.o \
m_ES_ExactExchange.o \
m_ES_occup.o             m_ES_WF_by_SDorCG.o      m_ES_WF_by_Davidson.o \
m_ES_RSB.o \
m_ES_WF_by_ModifiedDavidson.o m_ES_WF_by_RMM.o \
m_epc_potential.o \
m_Positron_Wave_Functions.o \
m_Charge_Density.o m_CD_Mag_Moment.o m_Orbital_Population.o      m_Dipole.o  m_CD_mixing.o \
m_PS_opencore.o \
m_ES_WF_mixing.o \
m_Screening_FFT.o        m_Screening.o      m_External_Potential.o \
m_ES_LHXC.o              m_ES_Intgr_VlhxcQlm.o    m_ES_IO.o \
m_Representation.o       m_OP_rotation.o          m_OP_decomp_band.o \
m_ES_WF_by_MatDiagon.o   m_ES_dos.o               m_Hubbard.o \
m_KineticEnergy_Density.o  \
m_KE_mixing.o \
m_vdWDF.o \
m_Ldos.o                 m_XC_Potential.o         \
string.o m_db.o \
m_PAW_Tecplot.o m_PAW_ChargeDensity.o m_PAW_Hartree.o  \
m_PAW_XC_Potential.o \
m_SpinOrbit_RadInt.o \
m_ES_Mag_Constraint.o  \
m_constraints.o \
m_Total_Energy.o \
m_OP_Moment.o \
m_Force.o                m_Stress.o m_ES_WF_by_submat.o\
m_UnitCell.o \
m_ELF.o                  m_Wannier.o \
m_Wannier90.o \
m_BerryPhase.o           m_BP_Properties.o \
m_Raman.o               m_Phonon.o \
m_LinearResponse_Control.o  \
m_ValenceBand_Spectrum.o   m_CoreLevel_Spectrum.o \
m_Excitation.o \
m_ES_occup_EPS.o         m_Epsilon_ek.o \
m_LinearResponse_Qpt.o \
m_ES_ChargeState.o \
m_Potential_Mixing.o       m_ThomasFermiW_Potential.o \
m_SpinOrbit_SecondVariation.o m_Crystal_Field.o \
m_PlaneWaveEDA.o \
m_Fcp.o m_CLS_dipquad.o m_Band_Unfolding.o m_Potential_Average.o

EKCAL_F_SUBROUTINES = Preparation.o \
InputData_Analysis.o           PseudoPotential_Construction.o

EKCAL_F_OTHERSUBS  = ekmain.o     constraint_main.o          Preparation_for_mpi.o \
Preparation_for_ESM.o \
scf_routines.o \
UnitaryTransform_WF.o \
bottom_Subroutines.o                   \
spline.o \
b_Crystal_Structure.o                  b_Electronic_Structure.o \
b_Words.o                              b_PseudoPotential.o \
b_PseudoPotential_EXX.o \
b_Fermi.o                              b_Kpoints.o \
b_PlaneWaveBasisSet.o                  b_Ionic_System.o \
b_XC_Potential.o                       b_PAW_XC_Potential.o \
b_XC_OmegaPBE.o  \
b_XC_metagga.o \
b_Ldos_f77.o \
input_interface.o                      Initialization.o \
Ewald_and_Structure_Factor.o \
Initial_Electronic_Structure.o         Renewal_of_WaveFunctions.o \
IterationNumbers_Setting.o \
ChargeDensity_Construction.o                 Renewal_of_Potential.o \
ChargeDensity_Mixing.o \
Renewal_of_Hubbard_Potential.o         Renewal_of_OccMat.o \
Convergence_Check.o                    Forces.o \
WriteDownData_onto_Files.o \
Initial_MD_Condition.o                 WriteDownData_onto_Files_ek.o\
Stress.o                               Postprocessing.o \
Finalization_of_mpi.o \
miscellaneous.o \
b_BerryPhase.o \
heap_sort.o                            real_spherical_harmonics.o \
Real_space_integ.o                     crotylm.o \
screening_correction.o \
mpi_dummy.o \
GaussLeg.o lib_int_deri_add.o \
Uramping.o \
ThomasFermiWeiz.o       Renewal_of_ChgCtrlParam.o vdW.o scdft_routines.o memsize.o

ifndef SX_DGEMM
EKCAL_OBJECTSF77 = \
b_PseudoPotential_f77.o \
b_Force_f77.o \
rmmsubs.o                              spg+tetra.o \
gncpp_xc_gga_rad.o  \
decfft_ent.o
else
EKCAL_OBJECTSF77 = \
b_PseudoPotential_f77.o \
b_Force_f77.o \
rmmsubs.o                              spg+tetra.o \
decfft_ent.o \
gncpp_xc_gga_rad.o  \
dgemm__.o 
endif


EPS_LOWER_MODULES = m_Const_Parameters.o   m_ErrorMessages.o m_Parallelization.o \
m_IterationNumbers.o

EPS_UPPER_MODULES = \
m_Spg_plus_Tetra_Common_Blocks.o \
m_Control_Parameters.o   m_Files.o                m_Timing.o \
m_Crystal_Structure.o    m_FFT.o                  m_Ionic_System.o \
m_CS_SpaceGroup.o        m_CS_Magnetic.o \
m_Orbital_QuantumNum.o  \
m_Kpoints.o              m_PseudoPotential.o      m_PlaneWaveBasisSet.o \
m_Realspace.o \
m_SpinOrbit_Potential.o  m_SpinOrbit_FromFile.o  \
m_ES_NonCollinear.o \
m_NonLocal_Potential.o   m_Electronic_Structure.o \
m_ES_nonlocal.o	 	 m_ES_ortho.o  m_ES_wf_extrpl.o m_ES_initialWF.o 	\
m_FiniteElectricField.o \
m_Positron_Wave_Functions.o \
m_ES_ExactExchange.o \
m_ES_occup.o             m_ES_WF_by_SDorCG.o      m_ES_WF_by_Davidson.o \
m_ES_RSB.o \
m_ES_WF_by_ModifiedDavidson.o m_ES_WF_by_RMM.o \
m_ES_LHXC.o              m_ES_Intgr_VlhxcQlm.o    m_ES_IO.o \
m_Representation.o       m_OP_rotation.o          m_OP_decomp_band.o \
m_ES_dos.o               m_Hubbard.o \
m_epc_potential.o \
m_vdWDF.o \
m_Charge_Density.o m_CD_Mag_Moment.o  m_Orbital_Population.o     m_Dipole.o m_CD_mixing.o \
m_XC_Potential.o \
m_PS_opencore.o \
m_ES_WF_mixing.o \
string.o m_db.o \
m_PAW_Tecplot.o m_PAW_ChargeDensity.o m_PAW_Hartree.o  \
m_PAW_XC_Potential.o \
m_SpinOrbit_RadInt.o \
m_ES_Mag_Constraint.o  \
m_Total_Energy.o \
m_OP_Moment.o \
m_Force.o          m_Stress.o      m_ES_WF_by_submat.o      m_ES_WF_by_MatDiagon.o \
m_UnitCell.o \
m_KineticEnergy_Density.o  \
m_KE_mixing.o \
m_Ldos.o                 m_ELF.o \
m_constraints.o \
m_BerryPhase.o           m_BP_Properties.o \
m_Raman.o       m_Phonon.o               \
m_Screening_FFT.o        m_Screening.o      m_External_Potential.o \
m_Wannier.o \
m_Wannier90.o \
m_ValenceBand_Spectrum.o   m_CoreLevel_Spectrum.o   \
m_Excitation.o \
m_CLS_dipquad.o m_ES_occup_EPS.o         m_Epsilon_ek.o \
m_LinearResponse_Control.o  \
m_LinearResponse_Qpt.o \
m_ES_ChargeState.o \
m_Potential_Mixing.o       m_ThomasFermiW_Potential.o \
m_SpinOrbit_SecondVariation.o m_Crystal_Field.o \
m_PlaneWaveEDA.o \
m_Fcp.o m_Band_Unfolding.o m_Potential_Average.o

EPS_F_SUBROUTINES = Preparation.o \
InputData_Analysis.o           PseudoPotential_Construction.o

EPS_F_OTHERSUBS  = epsmain.o      constraint_main.o     Preparation_for_mpi.o \
Preparation_for_ESM.o \
scf_routines.o \
UnitaryTransform_WF.o \
bottom_Subroutines.o                   \
spline.o \
b_Crystal_Structure.o                  b_Electronic_Structure.o \
b_Words.o                              b_PseudoPotential.o \
b_PseudoPotential_EXX.o \
b_Fermi.o                              b_Kpoints.o \
b_PlaneWaveBasisSet.o                  b_Ionic_System.o \
b_XC_Potential.o                       b_PAW_XC_Potential.o \
b_XC_OmegaPBE.o  \
b_XC_metagga.o \
b_Ldos_f77.o \
input_interface.o                      Initialization.o \
Ewald_and_Structure_Factor.o \
Initial_Electronic_Structure.o         Renewal_of_WaveFunctions.o \
IterationNumbers_Setting.o \
ChargeDensity_Construction.o                 Renewal_of_Potential.o \
ChargeDensity_Mixing.o \
Renewal_of_Hubbard_Potential.o         Renewal_of_OccMat.o \
Convergence_Check.o                    Forces.o \
WriteDownData_onto_Files.o \
Initial_MD_Condition.o                 WriteDownData_onto_Files_ek.o\
Stress.o                               Postprocessing.o \
Finalization_of_mpi.o \
miscellaneous.o \
b_BerryPhase.o \
heap_sort.o                            real_spherical_harmonics.o \
Real_space_integ.o                     crotylm.o \
screening_correction.o \
Initialization_Epsilon.o               Shift_Kpoint.o \
Reset_Kpoint.o                         Preparation_for_Calc_Epsilon.o \
Transition_moment_Epsilon.o            Calc_Epsilon.o \
Nonlinear_Optics_Epsilon.o             WriteDownData_onto_Files_Epsilon.o \
PseudoPotential_ek_Epsilon.o           Dealloc_Radr_and_Wos_Epsilon.o \
EPS_Prep_Check.o \
ThomasFermiWeiz.o         Renewal_of_ChgCtrlParam.o  \
mpi_dummy.o \
Uramping.o \
GaussLeg.o lib_int_deri_add.o vdW.o memsize.o scdft_routines.o

ifndef SX_DGEMM
EPS_OBJECTSF77 = \
b_PseudoPotential_f77.o \
b_Force_f77.o \
rmmsubs.o                              spg+tetra.o \
decfft_ent.o \
gncpp_xc_gga_rad.o  
else
EPS_OBJECTSF77 = \
b_PseudoPotential_f77.o \
b_Force_f77.o \
rmmsubs.o                              spg+tetra.o \
decfft_ent.o \
gncpp_xc_gga_rad.o  \
dgemm__.o
endif


TDLR_LOWER_MODULES = m_Const_Parameters.o   m_ErrorMessages.o m_Parallelization.o \
m_IterationNumbers.o

TDLR_UPPER_MODULES = \
m_Spg_plus_Tetra_Common_Blocks.o \
m_Control_Parameters.o   m_Files.o                m_Timing.o \
m_Crystal_Structure.o    m_FFT.o                  m_Ionic_System.o \
m_CS_SpaceGroup.o        m_CS_Magnetic.o \
m_Orbital_QuantumNum.o  \
m_Kpoints.o              m_PseudoPotential.o      m_PlaneWaveBasisSet.o \
m_Realspace.o \
m_SpinOrbit_Potential.o  m_SpinOrbit_FromFile.o  \
m_ES_NonCollinear.o \
m_NonLocal_Potential.o   m_Electronic_Structure.o \
m_ES_nonlocal.o	 	 m_ES_ortho.o  m_ES_wf_extrpl.o m_ES_initialWF.o 	\
m_FiniteElectricField.o \
m_Positron_Wave_Functions.o \
m_ES_ExactExchange.o \
m_ES_occup.o             m_ES_WF_by_SDorCG.o      m_ES_WF_by_Davidson.o \
m_ES_RSB.o \
m_ES_WF_by_ModifiedDavidson.o m_ES_WF_by_RMM.o \
m_ES_LHXC.o              m_ES_Intgr_VlhxcQlm.o    m_ES_IO.o \
m_Representation.o       m_OP_rotation.o          m_OP_decomp_band.o \
m_ES_dos.o               m_Hubbard.o \
m_epc_potential.o \
m_vdWDF.o \
m_Charge_Density.o m_CD_Mag_Moment.o m_Orbital_Population.o m_Dipole.o m_CD_mixing.o \
m_XC_Potential.o \
m_PS_opencore.o \
m_ES_WF_mixing.o \
string.o m_db.o \
m_PAW_Tecplot.o m_PAW_ChargeDensity.o m_PAW_Hartree.o  \
m_PAW_XC_Potential.o \
m_SpinOrbit_RadInt.o \
m_ES_Mag_Constraint.o  \
m_Total_Energy.o \
m_OP_Moment.o \
m_Force.o                m_Stress.o m_ES_WF_by_submat.o      m_ES_WF_by_MatDiagon.o \
m_UnitCell.o \
m_KineticEnergy_Density.o  \
m_KE_mixing.o \
m_Ldos.o                 m_ELF.o \
m_constraints.o \
m_BerryPhase.o           m_BP_Properties.o \
m_Raman.o          m_Phonon.o               \
m_Wannier.o \
m_Wannier90.o \
m_Screening_FFT.o        m_Screening.o      m_External_Potential.o \
m_Excitation.o \
m_CLS_dipquad.o m_ES_occup_EPS.o m_Epsilon_ek.o       \
m_LinearResponse_Control.o  \
m_ValenceBand_Spectrum.o  m_CoreLevel_Spectrum.o   \
m_Band_Unfolding.o \
m_ES_ChargeState.o \
m_LinearResponse_Qpt.o \
m_LinearResponse_Tools.o     m_LinearResponse_Density.o  \
m_LinearResponse_NonInt.o    m_LinearResponse_ALDA.o \
m_LinearResponse_Kernel.o    m_LinearResponse_BS.o \
m_LinearResponse_Spectrum.o \
m_Potential_Mixing.o       m_ThomasFermiW_Potential.o \
m_SpinOrbit_SecondVariation.o m_Crystal_Field.o \
m_PlaneWaveEDA.o \
m_Potential_Average.o

TDLR_F_SUBROUTINES = Preparation.o \
InputData_Analysis.o           PseudoPotential_Construction.o \

TDLR_F_OTHERSUBS  = tdlrmain.o     constraint_main.o    Preparation_for_mpi.o \
Preparation_for_ESM.o \
scf_routines.o \
UnitaryTransform_WF.o \
bottom_Subroutines.o                   \
spline.o \
b_Crystal_Structure.o                  b_Electronic_Structure.o \
b_Words.o                              b_PseudoPotential.o \
b_PseudoPotential_EXX.o \
b_Fermi.o                              b_Kpoints.o \
b_PlaneWaveBasisSet.o                  b_Ionic_System.o \
b_XC_Potential.o                       b_PAW_XC_Potential.o \
b_XC_OmegaPBE.o  \
b_XC_metagga.o \
b_Ldos_f77.o \
input_interface.o                      Initialization.o \
Ewald_and_Structure_Factor.o \
Initial_Electronic_Structure.o         Renewal_of_WaveFunctions.o \
IterationNumbers_Setting.o \
ChargeDensity_Construction.o                 Renewal_of_Potential.o \
ChargeDensity_Mixing.o \
Renewal_of_Hubbard_Potential.o         Renewal_of_OccMat.o \
Convergence_Check.o                    Forces.o \
WriteDownData_onto_Files.o \
Initial_MD_Condition.o                 WriteDownData_onto_Files_ek.o \
Stress.o                               Postprocessing.o \
Finalization_of_mpi.o \
miscellaneous.o \
b_BerryPhase.o \
heap_sort.o                            real_spherical_harmonics.o \
Real_space_integ.o                     crotylm.o \
screening_correction.o \
PseudoPotential_ek_Epsilon.o           \
mpi_dummy.o \
GaussLeg.o lib_int_deri_add.o \
ThomasFermiWeiz.o       Renewal_of_ChgCtrlParam.o \
b_LinearResponse_Kernel.o  b_LinearResponse_exc.o \
Uramping.o \
LinearResponse_Proc.o     LinearResponse_Spec.o vdW.o scdft_routines.o memsize.o

ifndef SX_DGEMM
TDLR_OBJECTSF77 = \
b_PseudoPotential_f77.o \
b_Force_f77.o \
rmmsubs.o                              spg+tetra.o \
decfft_ent.o \
gncpp_xc_gga_rad.o  
else
TDLR_OBJECTSF77 = \
b_PseudoPotential_f77.o \
b_Force_f77.o \
rmmsubs.o                              spg+tetra.o \
decfft_ent.o \
gncpp_xc_gga_rad.o  \
dgemm__.o
endif
